# Generated by Django 4.1.7 on 2023-04-24 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0002_profilutilisateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilUtilisateur',
        ),
    ]
