# Generated by Django 4.1.7 on 2023-04-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0004_cart_cartitem_cart_articles_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='article',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
